raedamdjango/cameras/urls.py
from django.urls import path
from django.conf.urls import url

from cameras.views import (
   CamListView, delete_camera, CamCreateView, create_new_camera, edit_url_camera, get_camera_position
)

from parking.views import (
   manage_spots
)

app_name = 'cameras'
urlpatterns = [
    path('new_camera/', CamCreateView.as_view(), name='new_camera'),
    path('manage_cameras/', CamListView.as_view(), name='manage_cameras'),
    path('new_camera/create_new_camera/',  create_new_camera, {}, name='create_new_camera'),
    path('edit_url_camera/',  edit_url_camera, {}, name='edit_url_camera'),
    path('get_camera_position/',  get_camera_position, {}, name='get_camera_position'),
    url(r'^manage_cameras/delete_camera/$', delete_camera, name='delete_camera'),

  #  url(r'^manage_cameras/manage_spots/$', manage_spots, name='manage_spots'),    
]

raedamdjango/core/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.views.generic.base import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(url='/parking/'), name='home'),
    path('parking/', include(
        ('parking.urls', 'parking'), namespace='parking')),
    path('cameras/', include(
        ('cameras.urls', 'cameras'), namespace='cameras')),
    path('pedestrian_detector/', include(
        ('pedestrian_detector.urls', 'pedestrian_detector'), namespace='pedestrian_detector')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.ENABLE_DEBUG_TOOLBAR:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

raedamdjango/parking/urls.py
from django.urls import path
from django.conf.urls import url

from parking.views import (
    Parking, Zones, add_new_zone, ManageSpots, remove_zone, manage_spots
    
)

app_name = 'parking'
urlpatterns = [
    path('', Parking.as_view(), name='spots'),
    path('zones/', Zones.as_view(), name='zones'),
    path('<str:id_cam>/manage_spots/', manage_spots, name='manage_spots'),   
    path('add_new_zone/', add_new_zone, {}, name='add_new_zone'),
    path('remove_zone/', remove_zone, {}, name='remove_zone')
]

raedamdjango/pedestrian_detector/urls.py
from django.urls import path
from django.conf.urls import url

from pedestrian_detector.views import (
   manage_detection, edit_roi, Detection, get_reports, LineChartJSONView, TemplateView,dashboard
)


line_chart = TemplateView.as_view(template_name='pedestrian_detector/manage_detection.html')
line_chart_json = LineChartJSONView.as_view()

app_name = 'pedestrian_detector'
urlpatterns = [
    path('<str:id_cam>/manage_detection/', manage_detection, name='manage_detection'),  
    path('<str:id_cam>/dashboard/', dashboard, name='dashboard'), 

    path('detection/', Detection.as_view(), name='detection'),
    path('line_chart_json/', line_chart_json, name='line_chart_json'),
    path('get_reports/', get_reports, {}, name='get_reports'),
    path('edit_roi/', edit_roi, {}, name='edit_roi'),
  #  url(r'^manage_cameras/manage_spots/$', manage_spots, name='manage_spots'),    
]

raedamdjango/templates/cam/cam_add.html
{% extends 'core/base.html' %}

{% load static %}

{% block preloads %}
<link rel="preload" as="style" href="{% static 'vendor/mapbox-gl-1.4.1/mapbox-gl.css' %}">
<link rel="preload" as="script" href="{% static 'vendor/mapbox-gl-1.4.1/mapbox-gl.js' %}">
{% endblock %}

{% block head %}
<link rel="stylesheet" href="{% static 'vendor/mapbox-gl-1.4.1/mapbox-gl.css' %}" type="text/css">
<script src="{% static 'vendor/mapbox-gl-1.4.1/mapbox-gl.js' %}" type="text/javascript"></script>
{% endblock %}

{% block main %}

    <style>
        #latitude, #longitude {display: inline-block; *display: inline; zoom: 1; vertical-align: top; font-size: 12px;}

        #latitude{
        
           
        }
        #longitude{
        
        }
    </style>

    <div id='gepoint' style=" height: 20%; width:100%;">
        longitude<input id="longitude" type="text"   disabled style=" height: 20%; width:10%;" />
        latitude<input id="latitude" type="text"  disabled style=" height: 20%; width:10%;" /> <br><br>
        url_cam<input id="url_cam" type="text" style="vertical-align: center; height: 20%; width:30%;" />

        <button id="probe_url_button" type="submit">Probe URL</button><br><br>
        TIPO DE CAMARA<select id="model_type_list">
            <option value="PR">PR</option>
            <option value="PD" selected="selected">PD</option>
        </select>
        <button id="sumbit_button" style="  width:100%;" type="submit">Guardar</button>
    </div>
    <div id='dummy_map' style="height:calc(150vh - 65px);">
        <div id='map' style="height: 100%; width:100%;"></div>
    </div>
    <div id='dummy_img' style="height:calc(150vh - 65px);" >
        <img class="img" id="image" width="800" height="400" src="" />
    </div>
    <script>



        var model_type_list = document.getElementById("model_type_list")
        CAM_DATA = {
            url: "",
            geopoint: "6.148355,-75.378672",
            model_detector:"PR"
        }
        var longitude_input = document.getElementById("longitude")
        var latitude_input = document.getElementById("latitude")
        latitude_input.value="6.148355"
        longitude_input.value="-75.378672"

        var url_cam = document.getElementById("url_cam")

        var dummy_map = document.getElementById("dummy_map")
        var dummy_img = document.getElementById("dummy_img")
        dummy_img.style.display = "none";

        var image = document.getElementById("image")
        var toggle=false

        var sumbit_button = document.getElementById("sumbit_button")
        sumbit_button.onclick=function(){
            CAM_DATA.url=url_cam.value
            CAM_DATA.model_detector=model_type_list.options[model_type_list.selectedIndex].value;
            CAM_DATA.geopoint=longitude_input.value+','+latitude_input.value
            console.log(CAM_DATA)
            $.getJSON("{% url 'cameras:create_new_camera' %}", CAM_DATA)
            .done(function (response) {
                location.replace("{% url 'cameras:manage_cameras' %}")
                console.log("response", response)
            })
            .fail(function (response, textStatus, error) {
                console.log(response, textStatus, error)
            })
        
        }

        var probe_url_button = document.getElementById("probe_url_button")
        probe_url_button.onclick=function(){

            if(toggle){
                toggle=false
                dummy_map.style.display = "block";
                dummy_img.style.display = "none";
                probe_url_button.innerHTML="Probe URL"
                

            }else{
                toggle=true
                image.src=url_cam.value
                probe_url_button.innerHTML="Back to map"
                dummy_map.style.display = "none";
                dummy_img.style.display = "block";
            }
            console.log(dummy_map.style.display)
        }
        var map_loaded = false
        mapboxgl.accessToken = '{{MAP_API}}'
        var map = new mapboxgl.Map({
            container: 'map',
            style: 'mapbox://styles/mapbox/streets-v11',
            center: [-75.378672, 6.148355],
            zoom: 18
        })

        var marker = new mapboxgl.Marker()
        .setLngLat( [-75.378672, 6.148355])
        .addTo(map);
        document.addEventListener('DOMContentLoaded', function() {
            if (navigator.geolocation) {
                navigator.geolocation.getCurrentPosition(function (position) {
                    map.setCenter([
                        position.coords.longitude,
                        position.coords.latitude
                    ])
                })
            } else {
                alert("Geolocation no disponible")
            }
        })

        
        map.on('load', function () {
            map_loaded = true
        })
        map.on('click', function (e) {
            marker.setLngLat([e.lngLat.lng,e.lngLat.lat]).addTo(map)
            latitude_input.value=e.lngLat.lat.toString()
            longitude_input.value=e.lngLat.lng.toString()
            $.ajax({
                url: "http://192.75.71.26/mjpg/video.mjpg",
                type:"GET",
                success: function(result){

                    console.log(result)
                },
                error: function(error){
                    console.log(error)
                }
            })
        });
    </script>
{% endblock  %}

raedamdjango/templates/cam/cam_delete.html
{% extends 'core/base.html' %}
{% block main %}
    <script>
     

    </script>
{% endblock  %}

raedamdjango/templates/cam/cam_list.html
{% extends 'core/base.html' %}
{% block title %}Home{% endblock title %}
{% block main %}
<a href="{% url 'cameras:new_camera' %}">NUEVA CAMARA</a>
{% for cams in object_list %}

<div class="card">

	<div class="card-header">
		<span class="font-weight-bold">{{ cams.url }}</span> &middot;
		<span class="text-muted"> {{ cams.geopoint }}</span>
	</div>

	{% if cams.model_detector in 'PR'  %} 
		<a href="{% url 'parking:manage_spots' id_cam=cams.id %}">configurar zonas {{ cams.model_detector }}</a> 
	{% endif %}
	
	{% if cams.model_detector in 'PD'  %} 
		<a href="{% url 'pedestrian_detector:manage_detection' id_cam=cams.id %}">configurar detection de personas {{ cams.model_detector }}</a> || 
		<a href="{% url 'pedestrian_detector:dashboard' id_cam=cams.id %}">dashboard</a> 
	{% endif %}

		| <a href="delete_camera/?id_cam={{ cams.id }}">Eliminar cámara</a>
		
</div>

<br />
{% endfor %}
{% endblock main %}