raedamdjango/cameras/urls.py
from django.urls import path
from django.conf.urls import url

from cameras.views import (
   CamListView, delete_camera, CamCreateView, create_new_camera, edit_url_camera, get_camera_position
)

from parking.views import (
   manage_spots
)

app_name = 'cameras'
urlpatterns = [
    path('new_camera/', CamCreateView.as_view(), name='new_camera'),
    path('manage_cameras/', CamListView.as_view(), name='manage_cameras'),
    path('new_camera/create_new_camera/',  create_new_camera, {}, name='create_new_camera'),
    path('edit_url_camera/',  edit_url_camera, {}, name='edit_url_camera'),
    path('get_camera_position/',  get_camera_position, {}, name='get_camera_position'),
    url(r'^manage_cameras/delete_camera/$', delete_camera, name='delete_camera'),

  #  url(r'^manage_cameras/manage_spots/$', manage_spots, name='manage_spots'),    
]

raedamdjango/core/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.views.generic.base import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(url='/parking/'), name='home'),
    path('parking/', include(
        ('parking.urls', 'parking'), namespace='parking')),
    path('cameras/', include(
        ('cameras.urls', 'cameras'), namespace='cameras')),
    path('pedestrian_detector/', include(
        ('pedestrian_detector.urls', 'pedestrian_detector'), namespace='pedestrian_detector')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.ENABLE_DEBUG_TOOLBAR:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

raedamdjango/parking/urls.py
from django.urls import path
from django.conf.urls import url

from parking.views import (
    Parking, Zones, add_new_zone, ManageSpots, remove_zone, manage_spots
    
)

app_name = 'parking'
urlpatterns = [
    path('', Parking.as_view(), name='spots'),
    path('zones/', Zones.as_view(), name='zones'),
    path('<str:id_cam>/manage_spots/', manage_spots, name='manage_spots'),   
    path('add_new_zone/', add_new_zone, {}, name='add_new_zone'),
    path('remove_zone/', remove_zone, {}, name='remove_zone')
]

raedamdjango/pedestrian_detector/urls.py
from django.urls import path
from django.conf.urls import url

from pedestrian_detector.views import (
   manage_detection, edit_roi, Detection, get_reports, LineChartJSONView, TemplateView,dashboard
)


line_chart = TemplateView.as_view(template_name='pedestrian_detector/manage_detection.html')
line_chart_json = LineChartJSONView.as_view()

app_name = 'pedestrian_detector'
urlpatterns = [
    path('<str:id_cam>/manage_detection/', manage_detection, name='manage_detection'),  
    path('<str:id_cam>/dashboard/', dashboard, name='dashboard'), 

    path('detection/', Detection.as_view(), name='detection'),
    path('line_chart_json/', line_chart_json, name='line_chart_json'),
    path('get_reports/', get_reports, {}, name='get_reports'),
    path('edit_roi/', edit_roi, {}, name='edit_roi'),
  #  url(r'^manage_cameras/manage_spots/$', manage_spots, name='manage_spots'),    
]

raedamdjango/parking/models.py
from django.db import models
from django.contrib.postgres.fields import ArrayField

from cameras.models import Camera


class ParkingCamera(models.Model):
    camera = models.ForeignKey(Camera, on_delete=models.CASCADE)
    spots = ArrayField(ArrayField(
        models.PositiveIntegerField(), size=4), default=list)

class ParkingCamera_reports(models.Model):
    camera = models.ForeignKey(Camera, on_delete=models.CASCADE)
    ocupied_spots=models.PositiveIntegerField()
    created = models.DateTimeField(auto_now_add=True)

raedamdjango/parking/views.py
import cv2
import time
import mrcnn
import numpy as np
import tensorflow as tf

from django.conf import settings

from tenant_schemas.utils import schema_context

from decimal import Decimal

from core.utils import coords_in_radius
from core.view_utils import BaseView
from parking.models import ParkingCamera
from cerebro import load_model, clean_boxes


if settings.ENABLE_DETECTOR and settings.IS_RUNSERVER:
    model = load_model()
    graph = tf.get_default_graph()


class Parking(BaseView):
    template = 'parking/home.html'

    def context(self):
        return {
            'MAP_API': settings.MAP_API,
            'FETCH_ZONES_INTERVAL': settings.FETCH_ZONES_INTERVAL,
            'MAX_ZONE_REQUESTS': settings.MAX_ZONE_REQUESTS,
        }

    def get(self, request):
        return self.render_template(request, self.context())


class Zones(BaseView):
    def get(self, request):
        lat = Decimal(request.GET.get('latitude'))
        lng = Decimal(request.GET.get('longitude'))

        with schema_context(request.schema_name):
            closest_cams = [
                cam for cam in ParkingCamera.objects.filter(is_active=True)
                if coords_in_radius(
                    cam.coords,
                    [lng, lat],
                    settings.CAMERA_RADIUS
                )
            ][:1]  # Hard limit number of detections

        assert len(closest_cams) < 2,\
            'Multiple cameras detection not implemented yet'

        parking_data = [] if closest_cams else {'error': 'No near cameras'}
        for cam in closest_cams:
            if not cam.spots:
                parking_data.append({
                    'error': f'ParkingCamera {cam.short_id} hasnt marked spots'
                })
                continue

            cap = cv2.VideoCapture(cam.url)
            success, frame = cap.read()
            if not success:
                parking_data.append({
                    'error': f'Couldnt read frame from camera {cam.short_id}'
                })
                continue

            rgb_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
            print(f"[+] Performing detection for cam '{cam.short_id}'")
            detection_start = time.time()
            with graph.as_default():
                results = model.detect([rgb_frame], verbose=0)
            print(f"[!] Detection took {time.time() - detection_start} secs")

            car_boxes = clean_boxes(
                results[0],
                settings.CAR_CLS_NAMES,
                settings.CAR_SCORE
            )
            car_spots = np.array(cam.spots)
            overlaps = mrcnn.utils.compute_overlaps(car_spots, car_boxes)

            for car_box in car_boxes:  # Detected cars
                y1, x1, y2, x2 = car_box
                cv2.rectangle(frame, (x1, y1), (x2, y2), (255, 0, 0), 3)

            cam_spots = {
                'shortid': cam.short_id,
                'coords': cam.coords,
                'total_spots': len(cam.spots),
                'free_spots': 0,
                'frame': cam.last_frame,
            }
            # Car spots
            for car_spot, overlap_areas in zip(car_spots, overlaps):
                y1, x1, y2, x2 = car_spot
                center = (int((x1 + x2) / 2), int((y1 + y2) / 2))
                radius = int((y2 - y1) / 2)
                free_spot = np.max(overlap_areas) < 0.2
                color = (0, 255, 0) if free_spot else (0, 0, 255)
                cam_spots['free_spots'] += 1 if free_spot else 0
                cv2.circle(frame, center, radius, color, 3)

            assert cam_spots['free_spots'] <= cam_spots['total_spots'],\
                f"'free_spots' ({cam_spots['free_spots']}) can't never "\
                f"be greater than 'total_spots' ({cam_spots['total_spots']})"

            parking_data.append(cam_spots)
            ratio = frame.shape[0] / frame.shape[1]
            resized = cv2.resize(frame, (640, int(ratio * 640)))
            cv2.imwrite(f"{settings.MEDIA_ROOT}/{cam.short_id}.png", resized)

        return self.render_json(parking_data, safe=False)

raedamdjango/templates/parking/cam_add.html
{% extends 'core/base.html' %}

{% load static %}

{% block preloads %}
<link rel="preload" as="style" href="{% static 'vendor/mapbox-gl-1.4.1/mapbox-gl.css' %}">
<link rel="preload" as="script" href="{% static 'vendor/mapbox-gl-1.4.1/mapbox-gl.js' %}">
{% endblock %}

{% block head %}
<link rel="stylesheet" href="{% static 'vendor/mapbox-gl-1.4.1/mapbox-gl.css' %}" type="text/css">
<script src="{% static 'vendor/mapbox-gl-1.4.1/mapbox-gl.js' %}" type="text/javascript"></script>
{% endblock %}

{% block main %}

    <style>
        #latitude, #longitude {display: inline-block; *display: inline; zoom: 1; vertical-align: top; font-size: 12px;}

        #latitude{
        
           
        }
        #longitude{
        
        }
    </style>

    <div id='gepoint' style=" height: 20%; width:100%;">
        longitude<input id="longitude" type="text"   disabled style=" height: 20%; width:10%;" />
        latitude<input id="latitude" type="text"  disabled style=" height: 20%; width:10%;" /> <br><br>
        url_cam<input id="url_cam" type="text" style="vertical-align: center; height: 20%; width:30%;" />

        <button id="probe_url_button" type="submit">Probe URL</button><br><br>
        
        <button id="sumbit_button" style="  width:100%;" type="submit">Guardar</button>
    </div>
    <div id='dummy_map' style="height:calc(100vh - 65px);">
        <div id='map' style="height: 100%; width:100%;"></div>
    </div>
    <div id='dummy_img' style="height:calc(100vh - 65px);" >
        <img class="img" id="image" width="800" height="400" src="" />
    </div>
    <script>

        CAM_DATA = {
            url: "",
            geopoint: "6.148355,-75.378672"
        }
        var longitude_input = document.getElementById("longitude")
        var latitude_input = document.getElementById("latitude")
        latitude_input.value="6.148355"
        longitude_input.value="-75.378672"

        var url_cam = document.getElementById("url_cam")

        var dummy_map = document.getElementById("dummy_map")
        var dummy_img = document.getElementById("dummy_img")
        dummy_img.style.display = "none";

        var image = document.getElementById("image")
        var toggle=false

        var sumbit_button = document.getElementById("sumbit_button")
        sumbit_button.onclick=function(){
            CAM_DATA.url=url_cam.value
            CAM_DATA.geopoint=latitude_input.value+','+longitude_input.value
            $.getJSON("{% url 'parking:create_new_camera' %}", CAM_DATA)
            .done(function (response) {
                console.log("response", response)
            })
            .fail(function (response, textStatus, error) {
                console.log(response, textStatus, error)
            })
        
        }

        var probe_url_button = document.getElementById("probe_url_button")
        probe_url_button.onclick=function(){

            if(toggle){
                toggle=false
                dummy_map.style.display = "block";
                dummy_img.style.display = "none";
                probe_url_button.innerHTML="Probe URL"
                

            }else{
                toggle=true
                image.src=url_cam.value
                probe_url_button.innerHTML="Back to map"
                dummy_map.style.display = "none";
                dummy_img.style.display = "block";
            }
            console.log(dummy_map.style.display)
        }
        var map_loaded = false
        mapboxgl.accessToken = '{{MAP_API}}'
        var map = new mapboxgl.Map({
            container: 'map',
            style: 'mapbox://styles/mapbox/streets-v11',
            center: [-75.378672, 6.148355],
            zoom: 18
        })

        var marker = new mapboxgl.Marker()
        .setLngLat( [-75.378672, 6.148355])
        .addTo(map);
        document.addEventListener('DOMContentLoaded', function() {
            if (navigator.geolocation) {
                navigator.geolocation.getCurrentPosition(function (position) {
                    map.setCenter([
                        position.coords.longitude,
                        position.coords.latitude
                    ])
                })
            } else {
                alert("Geolocation no disponible")
            }
        })

        
        map.on('load', function () {
            map_loaded = true
        })
        map.on('click', function (e) {
            marker.setLngLat([e.lngLat.lng,e.lngLat.lat]).addTo(map)
            latitude_input.value=e.lngLat.lat.toString()
            longitude_input.value=e.lngLat.lng.toString()
            $.ajax({
                url: "http://192.75.71.26/mjpg/video.mjpg",
                type:"GET",
                success: function(result){

                    console.log(result)
                },
                error: function(error){
                    console.log(error)
                }
            })
        });
    </script>
{% endblock  %}

raedamdjango/templates/parking/home.html
{% extends 'core/base.html' %}
{% load static %}

{% block title %}Busca tu celda{% endblock %}

{% block head %}
<link rel="preload" as="style" href="{% static 'vendor/mapbox-gl-1.4.1/mapbox-gl.css' %}">
<link rel="preload" as="script" href="{% static 'vendor/mapbox-gl-1.4.1/mapbox-gl.js' %}">

<link rel="stylesheet" href="{% static 'vendor/mapbox-gl-1.4.1/mapbox-gl.css' %}" type="text/css">
<script src="{% static 'vendor/mapbox-gl-1.4.1/mapbox-gl.js' %}" type="text/javascript"></script>
{% endblock %}

{% block main %}
<div id='map' style="height:calc(100vh - 65px);"></div>
{% endblock %}

{% block bodyafter %}
<script>
var map_loaded = false
var zones_timer = undefined
var request_counter = 1
var cameras = {}
var camera_information = {}


mapboxgl.accessToken = '{{MAP_API}}'
var map = new mapboxgl.Map({
    container: 'map',
    style: 'mapbox://styles/mapbox/streets-v11',
    center: [-75.378672, 6.148355],
    zoom: 16
})


document.addEventListener('DOMContentLoaded', function() {
    if (navigator.geolocation) {
        navigator.geolocation.getCurrentPosition(function (position) {
            map.setCenter([
                position.coords.longitude,
                position.coords.latitude
            ])
        })
    } else {
        alert("Geolocation no disponible")
    }
})


map.on('load', function () {
    map_loaded = true
    zones_timer = setInterval(fetchZones, {{FETCH_ZONES_INTERVAL}})
    fetchZones()
    GetCameraPosition()
})

function GetCameraPosition()
{
    $.getJSON('{% url "cameras:get_camera_position" %}').done( 
        function(cams) {
            console.log(cams.cameras)
            camera_information=cams
            cams.cameras.forEach(function (cam) {

                var marker = undefined
                var marker_elem = undefined
                var marker_subtitle = undefined
                var popup = undefined

                if (cam.shortid in cameras) {
                    marker = cameras[cam.shortid]['marker']
                    marker_elem = cameras[cam.shortid]['marker_elem']
                    marker_subtitle = cameras[cam.shortid]['marker_subtitle']
                    popup = cameras[cam.shortid]['popup']
                } else {
                    marker_elem = document.createElement('div')
                    marker_elem.className = 'camera_marker'

                    marker_subtitle = document.createElement('div')
                    marker_subtitle.className = 'marker_subtitle'
                    marker_elem.appendChild(marker_subtitle)
                    console.log(cam.coords)
                    popup = new mapboxgl.Popup({offset: 25})
                    marker = new mapboxgl.Marker(marker_elem)
                        .setLngLat(cam.coords)
                        .setPopup(popup)
                        .addTo(map)

                    cameras[cam.shortid] = {marker, marker_elem, marker_subtitle, popup}
                }
            })
        }).fail(
        function(response, textStatus, error) {
            console.log(response, textStatus, error)
        }
    )
}
function fetchZones() {
    if (!map_loaded) return

    if (++request_counter > {{MAX_ZONE_REQUESTS}})
        clearInterval(zones_timer)

    const map_center = map.getCenter()
    const data = {
        latitude: map_center.lat,
        longitude: map_center.lng
    }
/*
    $.getJSON('{% url "parking:zones" %}', data).done(updateCameras).fail(
        function(response, textStatus, error) {
            console.log(response, textStatus, error)
        }
    )*/
    $.getJSON('{% url "pedestrian_detector:detection" %}', data).done(updateCameras).fail(
        function(response, textStatus, error) {
            console.log(response, textStatus, error)
        }
    )
}


function updateCameras(cams) {
    console.log('CAMS', cams)

    cams.forEach(function (cam) {
        var marker = undefined
        var marker_elem = undefined
        var marker_subtitle = undefined
        var popup = undefined

        if (cam.shortid in cameras) {
            marker = cameras[cam.shortid]['marker']
            marker_elem = cameras[cam.shortid]['marker_elem']
            marker_subtitle = cameras[cam.shortid]['marker_subtitle']
            popup = cameras[cam.shortid]['popup']
        } else {
            marker_elem = document.createElement('div')
            marker_elem.className = 'camera_marker'

            marker_subtitle = document.createElement('div')
            marker_subtitle.className = 'marker_subtitle'
            marker_elem.appendChild(marker_subtitle)
            console.log(cam.coords)
            popup = new mapboxgl.Popup({offset: 25})
            marker = new mapboxgl.Marker(marker_elem)
                .setLngLat(cam.coords)
                .setPopup(popup)
                .addTo(map)

            cameras[cam.shortid] = {marker, marker_elem, marker_subtitle, popup}
        }
        if(cam.model_detector=="PR"){
            marker_elem.style.backgroundColor = cam.free_spots > 0 ? "#0f04" : "#f004"
            marker_subtitle.innerText = (cam.total_spots - cam.free_spots) + '/' + cam.total_spots
        }
        popup.setHTML('<div>'+
  '<p>FREE SPOTS: </p>'+
  '<img src="data:image/jpeg;base64,'+cam.frame_base64+'" width="800" height="400" alt="DETECTION" />'+'</div>')
    })
}

</script>
{% endblock %}

raedamdjango/templates/parking/manage_spots.html
{% extends 'core/base.html' %}

{% block main %}
<style>
    h1 {
        font-family: sans-serif;
        font-size: 64px;
        color: #CCC;
        padding: 5px;
        margin: 5px;
    }
    ul {
        padding: 0;
        margin: 10px;
        overflow-y: scroll;
        height: 400px;
    }
    li:focus {
        background: lightgreen;
    }
    li {
        font-family: sans-serif;
        background-color: gold;
        float: left;
        clear: both;
        padding: 5px;
        list-style-type: none;
        margin: 10px;
        border-radius: 5px;
    }
    #canvas_container, #menu_container {
        display: inline-block;
        *display: inline;
        zoom: 1;
        vertical-align: top;
        font-size: 12px;
    }
    #img {
        position: absolute;
        z-index: 1;
        border-radius: 20px;
    }
    #canvas_container {
        display:inline-block;
        width:800px; 
        height:400px;
        margin: 0 auto; 
        background: black; 
        position:relative; 
        border:0px solid black; 
        border-radius: 20px; 
        box-shadow: 0 5px 50px #333
    }
    #menu_container{

        border: 3px solid green;
        width:25%; 
    }
    #myCanvas{
        position:relative;
        z-index:20;
    }
    #main_container {
        height: 100px;
        width:100%;
        font-size: 0;
    }
    #add_spot_button, #remove_spot_button {
        display: inline-block;
        *display: inline;
        zoom: 1;
        vertical-align: top;
        font-size: 12px;
    }
    #add_spot_button {
        margin: auto;
        width: 45%;
        border: 3px solid green;
        padding: 10px;
    }
    #remove_spot_button {
        margin: auto;
        width: 45%;
        border: 3px solid green;
        padding: 10px;
    }
</style>

url_cam<input id="url_cam" type="text" value= "{{ camera.fields.url }}" disabled style="vertical-align: center; height: 10%; width:30%;"/>
<button id="edit_url_button" type="submit">Edit url</button>
<div id="canvas_container">
    <img id="img" width="800" height="400" src="{{ camera.fields.url }}" />
    <canvas id="myCanvas" width="800" height="400">
        Your browser does not support the HTML5 canvas tag.
    </canvas> 
   
</div>
<div id="menu_container">
    <ul id='ul_list'></ul>
</div>
<button id="add_spot_button" type="button" >Add new spot!</button>
<button id="remove_spot_button" type="button" >Remove selected spot!</button>


<script>
    console.log({{ spots.fields.spots|safe }})
    SPOT_DATA = {
        id_cam: "{{ camera.pk }}",
        x: 0,
        y: 0,
        width: 0,
        height: 0,
        spots: [],
        url:"{{ camera.fields.url }}"
    }
    SPOT_DATA_CONTAINER = {SPOT_DATA}
    var toggle=false
    var image = document.getElementById("img")
    var edit_url_button = document.getElementById("edit_url_button")
    edit_url_button.onclick=function(){
        if(toggle){
            edit_url_button.innerHTML="Edit url"
            SPOT_DATA.url=url_cam.value
            image.src=url_cam.value
            toggle=false
            url_cam.disabled=true
            $.getJSON("{% url 'cameras:edit_url_camera' %}", SPOT_DATA)
            .done(function (response) {
                console.log("response", response)
            })
            .fail(function (response, textStatus, error) {
                console.log(response, textStatus, error)
            })
        }else{
            edit_url_button.innerHTML="Save url"
            toggle=true
            url_cam.disabled=false
        }
    }
    var url_cam = document.getElementById("url_cam")
    url_cam.value="{{ camera.fields.url }}"
    //ADD NEW ZONE LISTENEER
    var add_spot_button = document.getElementById("add_spot_button")
    add_spot_button.onclick = function(e){

        SPOT_DATA.width = Math.abs(endX-initX)
        SPOT_DATA.height = Math.abs(endY-initY)

        if(endX - initX < 0){
            initX = endX
        }
        if(endY - initY < 0){
            initY = endY
        }
        SPOT_DATA.x = initX
        SPOT_DATA.y = initY
        SPOT_DATA.spots.push([
            SPOT_DATA.x,
            SPOT_DATA.y,
            SPOT_DATA.width,
            SPOT_DATA.height
        ])
        if(Math.abs(SPOT_DATA.width) > 0 && Math.abs(SPOT_DATA.height) > 0){

            SPOT_DATA_CONTAINER.SPOT_DATA = JSON.stringify(SPOT_DATA)
            $.getJSON("{% url 'parking:add_new_zone' %}", SPOT_DATA_CONTAINER)
            .done(function (response) {
                var listItem = document.createElement("li")
                listItem.textContent = SPOT_DATA.spots[SPOT_DATA.spots.length-1]
                listItem.tabIndex="1"
                ul.appendChild(listItem)
                draw_spots(-1)
            })
            .fail(function (response, textStatus, error) {
                console.log(response, textStatus, error)
            })
        }
    }

    //REMOVE ZONE LISTENEER
    var remove_spot_button = document.getElementById("remove_spot_button")
    remove_spot_button.onclick = function(e){
        if(ul_selection != -1){
            var new_spots = []
            for (var i = 0; i < SPOT_DATA.spots.length; i++) {
                if(i != ul_selection)
                    new_spots.push(SPOT_DATA.spots[i])
            }
            SPOT_DATA.spots = new_spots
            SPOT_DATA_CONTAINER.SPOT_DATA = JSON.stringify(SPOT_DATA)

            $.getJSON("{% url 'parking:remove_zone' %}", SPOT_DATA_CONTAINER)
            .done(function (response) {
                console.log("response", response)
                ul.removeChild(ul.childNodes[ul_selection+1])
                draw_spots(-1)
            })
            .fail(function (response, textStatus, error) {
                console.log(response, textStatus, error)
            })
        }
    }

    //CANVAS INIT
    var canvas = document.getElementById("myCanvas")
    var ctx = canvas.getContext("2d")
    ctx.beginPath()
    
    //USEFUL VARIABLES INIT
    var initX = 0
    var initY = 0
    var endX = 0
    var endY = 0
    var isMouseDown = false

    canvas.addEventListener('mousedown', function(e){
        initX = e.offsetX
        initY = e.offsetY
        isMouseDown = true
            console.log(endX,endY)
    })

    canvas.addEventListener('mouseup', function(e){
        isMouseDown = false
            console.log(endX,endY)
    })

    canvas.addEventListener('mousemove', function(e){
        if (isMouseDown) {
            console.log(endX,endY)
            endX = e.offsetX
            endY = e.offsetY

            ctx.clearRect(0, 0, canvas.width, canvas.height)
            draw_spots(-1)
            ctx.beginPath()

            ctx.strokeStyle = 'red'
            ctx.lineWidth = 5
            ctx.rect(initX, initY, endX - initX, endY - initY)
            ctx.stroke()
        }
    })

    SPOT_DATA.spots = {{ spots.fields.spots }}
    console.log({{ spots.fields.spots }})
    function draw_spots(selection){

        ctx.clearRect(0, 0, canvas.width, canvas.height)
        if (selection == -1) {
            var i
            for (i = 0; i < SPOT_DATA.spots.length; i++) {
                ctx.beginPath()
                ctx.strokeStyle = 'black'
                ctx.lineWidth = 3
                ctx.rect(
                    SPOT_DATA.spots[i][0],
                    SPOT_DATA.spots[i][1],
                    SPOT_DATA.spots[i][2],
                    SPOT_DATA.spots[i][3]
                )
                ctx.stroke()
            }
        } else {
            for (i = 0; i < SPOT_DATA.spots.length; i++) {
                ctx.beginPath()
                if (i == selection) {
                    ctx.strokeStyle = 'red'
                    ctx.lineWidth = 8
                } else {
                    ctx.strokeStyle = 'black'
                    ctx.lineWidth = 3
                }
                ctx.rect(
                    SPOT_DATA.spots[i][0],
                    SPOT_DATA.spots[i][1],
                    SPOT_DATA.spots[i][2],
                    SPOT_DATA.spots[i][3]
                )
                ctx.stroke()
            }
        }
    }
    draw_spots(-1)

    var ul = document.getElementById("ul_list")
    var ul_selection = -1
    ul.onclick = function(event) {
        var target = event.target
        ul_selection = $(target).index()
        draw_spots(ul_selection)
    }
    for (var i = 0; i < SPOT_DATA.spots.length; i++) {
        var listItem = document.createElement("li")
        listItem.textContent = SPOT_DATA.spots[i]
        listItem.tabIndex="1"
        ul.appendChild(listItem)
    }
</script>
{% endblock %}
       