raedamdjango/cameras/urls.py
from django.urls import path
from django.conf.urls import url

from cameras.views import (
   CamListView, delete_camera, CamCreateView, create_new_camera, edit_url_camera, get_camera_position
)

from parking.views import (
   manage_spots
)

app_name = 'cameras'
urlpatterns = [
    path('new_camera/', CamCreateView.as_view(), name='new_camera'),
    path('manage_cameras/', CamListView.as_view(), name='manage_cameras'),
    path('new_camera/create_new_camera/',  create_new_camera, {}, name='create_new_camera'),
    path('edit_url_camera/',  edit_url_camera, {}, name='edit_url_camera'),
    path('get_camera_position/',  get_camera_position, {}, name='get_camera_position'),
    url(r'^manage_cameras/delete_camera/$', delete_camera, name='delete_camera'),

  #  url(r'^manage_cameras/manage_spots/$', manage_spots, name='manage_spots'),    
]

raedamdjango/core/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.views.generic.base import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(url='/parking/'), name='home'),
    path('parking/', include(
        ('parking.urls', 'parking'), namespace='parking')),
    path('cameras/', include(
        ('cameras.urls', 'cameras'), namespace='cameras')),
    path('pedestrian_detector/', include(
        ('pedestrian_detector.urls', 'pedestrian_detector'), namespace='pedestrian_detector')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.ENABLE_DEBUG_TOOLBAR:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

raedamdjango/pedestrian_detector/urls.py
from django.urls import path
from django.conf.urls import url

from pedestrian_detector.views import (
   manage_detection, edit_roi, Detection, get_reports, LineChartJSONView, TemplateView,dashboard
)


line_chart = TemplateView.as_view(template_name='pedestrian_detector/manage_detection.html')
line_chart_json = LineChartJSONView.as_view()

app_name = 'pedestrian_detector'
urlpatterns = [
    path('<str:id_cam>/manage_detection/', manage_detection, name='manage_detection'),  
    path('<str:id_cam>/dashboard/', dashboard, name='dashboard'), 

    path('detection/', Detection.as_view(), name='detection'),
    path('line_chart_json/', line_chart_json, name='line_chart_json'),
    path('get_reports/', get_reports, {}, name='get_reports'),
    path('edit_roi/', edit_roi, {}, name='edit_roi'),
  #  url(r'^manage_cameras/manage_spots/$', manage_spots, name='manage_spots'),    
]

raedamdjango/pedestrian_detector/models.py
from django.db import models
from cameras.models import Camera
from django.contrib.postgres.fields import ArrayField


class PedestrianCamera(models.Model):
    camera = models.ForeignKey(Camera, on_delete=models.CASCADE)
    detection_zone =ArrayField(
        models.PositiveIntegerField(), size=4)

class PedestrianCamera_reports(models.Model):
    camera = models.ForeignKey(Camera, on_delete=models.CASCADE)
    amount_of_people=models.PositiveIntegerField()
    created = models.DateTimeField(auto_now_add=True)
    

raedamdjango/pedestrian_detector/views.py
import cv2
import json
import time
import mrcnn
import numpy as np
import tensorflow as tf

from django.db import connection
from django.conf import settings
from django.views import View
from django.shortcuts import render
from django.http import JsonResponse
from django.utils.dateparse import parse_datetime

from typing import Dict, Any
from decimal import Decimal
# UTILS FUNCTIONS
from core.utils import coords_in_radius
# ALL MODELS
from pedestrian_detector.models import PedestrianCamera_reports
from pedestrian_detector.models import PedestrianCamera
from cameras.models import Camera
# MAIN DETECTON CLASS
from cerebro import load_model, clean_boxes
# IMAGE TO STRING
from django.core.serializers import serialize
import base64
# CHARTS
from datetime import datetime, timedelta
from random import seed
from random import random
from random import randint
from django.views.generic import TemplateView
from chartjs.views.lines import BaseLineChartView

if settings.ENABLE_DETECTOR and ~settings.ENABLE_FALSE_DETECTOR and settings.IS_RUNSERVER:
    model = load_model()
    graph = tf.get_default_graph()
# Create your views here.

seed(12)

def manage_detection(request, id_cam):

    data = {'detection_zone': [], 'camera': []}
    detection_zone = PedestrianCamera.objects.filter(camera_id__exact=id_cam)
    camera = Camera.objects.filter(pk=id_cam)
    print(detection_zone)
    detection_zone_json = json.loads(serialize('json', detection_zone))[0]
    camera_json = json.loads(serialize('json', camera))[0]

    detection_zone_json['fields']['detection_zone'] = str(
        detection_zone.values('detection_zone').values()[0]['detection_zone'])

    data['detection_zone'] = detection_zone_json
    data['camera'] = camera_json
    print(data)
    return render(request, 'pedestrian_detector/manage_detection.html', data)


def edit_roi(request):
    id_cam = request.GET.get('id_cam')
    x = request.GET.get('x')
    y = request.GET.get('y')
    width = request.GET.get('width')
    height = request.GET.get('height')
    pedestrian_obj = PedestrianCamera.objects.filter(
        camera_id__exact=id_cam).update(detection_zone=[x, y, width, height])
    return JsonResponse({"ok": "ok"}, safe=False)


class BaseView(View):
    def global_context(self, request=None):
        return {
            'DEBUG': settings.DEBUG,
            'view': f'{self.__module__}.{self.__class__.__name__}',
            'sql_queries': len(connection.queries),
        }

    def render_template(self, request, context=None, template=None):
        return render(request, template or self.template, {
            **self.global_context(),
            **(context or {}),
        })

    def render_json(self, json_dict: Dict[str, Any], **kwargs):
        return JsonResponse(json_dict, **kwargs)


def get_reports(request):
    result = []
    pederestian_reports = PedestrianCamera_reports.objects.filter(
        camera_id__exact=cam.id)[0]

    pederestian_reports = json.loads(serialize('json', pederestian_reports))[0]
    print(pederestian_reports)

    result.append({'name': 'name', "data": 'data'})
    return result


class Detection(BaseView):
    def get(self, request):
        lat = Decimal(request.GET.get('latitude'))
        lng = Decimal(request.GET.get('longitude'))

        closest_cams = [
            cam for cam in Camera.objects.filter(is_active=True, model_detector=Camera.PEDESTRIAN)
            if coords_in_radius(
                cam.coords,
                [lng, lat],
                settings.CAMERA_RADIUS
            ) and cam.model_detector == Camera.PEDESTRIAN
        ][:1]  # Hard limit number of detections

        assert len(closest_cams) < 2,\
            'Multiple cameras detection not implemented yet'
        print(closest_cams)

        pedestrian_data = [] if closest_cams else {'error': 'No near cameras'}
        for cam in closest_cams:
           
            print(type(cam.url))
            camera_of_spots = PedestrianCamera.objects.filter(
                camera_id__exact=cam.id)[0]

            cap = cv2.VideoCapture(cam.url)
            success, frame = cap.read()
            if not success:
                pedestrian_data.append({
                    'error': f'Couldnt read frame from camera {cam.short_id}'
                })
                continue

            rgb_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
            print(f"[+] Performing detection for cam '{cam.short_id}'")
            detection_start = time.time()
            if settings.ENABLE_FALSE_DETECTOR:
                ammount=randint(3, 10)
                print("\nammount")
                print(ammount)
                cam_info = {
                    'shortid': cam.short_id,
                    'coords': cam.coords,
                    'ammount': ammount,
                    'frame_base64': ""
                }
                park_report_aux = PedestrianCamera_reports(
                    camera=cam, amount_of_people=ammount)
                park_report_aux.save()
                pedestrian_data.append(cam_info)
                pedestrian_data.append(cam_info)
            else:
                with graph.as_default():
                    results = model.detect([rgb_frame], verbose=0)
                print(f"[!] Detection took {time.time() - detection_start} secs")

                boxes = clean_boxes(
                    results[0],
                    settings.PEDESTRIAN_CLS_NAMES,
                    settings.PEDESTRIAN_SCORE
                )
                aux = 0
                for box in boxes:  # Detected cars
                    print(box)
                    y1, x1, y2, x2 = box
                    cv2.rectangle(frame, (x1, y1), (x2, y2), (255, 0, 0), 3)
                    aux = aux+1

                cam_info = {
                    'shortid': cam.short_id,
                    'coords': cam.coords,
                    'ammount': aux,
                    'frame_base64': ""
                }
                park_report_aux = PedestrianCamera_reports(
                    camera=cam, amount_of_people=cam_info['ammount'])
                park_report_aux.save()
                pedestrian_data.append(cam_info)

                ratio = frame.shape[0] / frame.shape[1]
                resized = cv2.resize(frame, (640, int(ratio * 640)))

                retval, buffer = cv2.imencode('.jpg', resized)
                jpg_as_text = base64.b64encode(buffer)
                txt = str(jpg_as_text)
                cam_info['frame_base64'] = txt[2:-1]
                print(f"{settings.MEDIA_ROOT}/{cam.short_id}.png")
                cv2.imwrite(f"{settings.MEDIA_ROOT}/{cam.short_id}.png", resized)

        return self.render_json(pedestrian_data, safe=False)
# CHARTS


class LineChartJSONView(BaseLineChartView):
    def get_labels(self):
        """Return 7 labels for the x-axis."""
        return ["January", "February", "March", "April", "May", "June", "July"]

    def get_providers(self):
        """Return names of datasets."""
        return ["Central", "Eastside", "Westside"]

    def get_data(self):
        """Return 3 datasets to plot."""

        return [[75, 44, 92, 11, 44, 95, 35],
                [41, 92, 18, 3, 73, 87, 92],
                [87, 21, 94, 3, 90, 13, 65]]


line_chart = TemplateView.as_view(template_name='line_chart.html')
line_chart_json = LineChartJSONView.as_view()


def dashboard(request, id_cam):

    today = datetime.now()
    timestamp_to = datetime.now() + timedelta(days=3)
    timestamp_from = datetime.now() - timedelta(days=3)
    print('\ntimestamp_to\n')
    print(timestamp_to)
    print('\ntimestamp_from\n')
    print(timestamp_from)

    # read data
    values = []
    categories=[]

    pedestrian_reports = PedestrianCamera_reports.objects.filter(
        camera_id__exact=id_cam,
        created__gte = timestamp_from,
        created__lt = timestamp_to).distinct()

    pedestrian_reports = json.loads(serialize('json', pedestrian_reports))

    print(pedestrian_reports)
    time_aux=timestamp_from
    aux_avg=0
    count_avg=0
    for i in pedestrian_reports:
        i['fields']['created']=i['fields']['created'][0:-2].replace("T", " ", 1)
        aux_i=datetime.strptime(i['fields']['created'], '%Y-%m-%d %H:%M:%S.%f')
        
        print(aux_i)
        if(aux_i>=time_aux 
            and aux_i<time_aux+timedelta(minutes=15)):
            aux_avg+=i['fields']['amount_of_people']
            count_avg=count_avg+1
            print(count_avg)
        else:
            if(count_avg>0):
                values.append(aux_avg/count_avg)
                categories.append(str(time_aux))
                aux_avg=0
            time_aux=time_aux+timedelta(minutes=15)    

        
    '''for i in pedestrian_reports:
        values.append(i['fields']['amount_of_people'])
        categories.append(i['fields']['created'])'''

    context = {"categories": categories, 'values': values}
    print(context)
    return render(request, 'pedestrian_detector/dashboard.html', context=context)

raedamdjango/templates/pedestrian_detector/dashboard.html
{% extends 'core/base.html' %}
{% load staticfiles %}
{% block main %}

<div class="container-fluid">
    <div class="row">
            <!-- Highcharts display -->
            <div class="border" id="container" style="width: 800px; height: 400px; margin: 0 auto"></div>

         
            </main>
    </div>
</div>

<!-- Chartjs libraries -->
<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>
<script src="https://code.highcharts.com/modules/export-data.js"></script>

<script>
    _categories = {{ categories | safe }};
    _values = {{ values | safe }};

    Highcharts.chart('container', {
        chart: {
            type: 'column'
        },
        title: {
            text: 'People in your bussiness history (Last Week)'
        },
        subtitle: {
            text: ')'
        },
        xAxis: {
            categories: _categories,
            crosshair: true
        },
        yAxis: {
            min: 0,
            title: {
                text: 'Ammount of people'
            }
        },
        tooltip: {
            headerFormat: '<span style="font-size:10px">{point.key}</span><table>',
            pointFormat: '<tr><td style="color:{series.color};padding:0">{series.name}: </td>' +
                '<td style="padding:0"><b>{point.y:.1f} </b></td></tr>',
            footerFormat: '</table>',
            shared: true,
            useHTML: true
        },
        plotOptions: {
            column: {
                pointPadding: 0.2,
                borderWidth: 0
            }
        },
        series: [{
            name: 'Count',
            data: _values

        }]
    });
</script>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"
    integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut"
    crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"
    integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k"
    crossorigin="anonymous"></script>

{% endblock %}

raedamdjango/templates/pedestrian_detector/manage_detection.html
{% extends 'core/base.html' %}
{% load staticfiles %}
{% block main %}
<style>
    h1 {
        font-family: sans-serif;
        font-size: 64px;
        color: #CCC;
        padding: 5px;
        margin: 5px;
    }
    #img {
        position: absolute;
        z-index: 1;
        border-radius: 20px;
    }
    #canvas_container {
        display:inline-block;
        width:800px; 
        height:400px;
        margin: 0 auto; 
        background: black; 
        position:relative; 
        border:0px solid black; 
        border-radius: 20px; 
        box-shadow: 0 5px 50px #333
    }
    #myCanvas{
        position:relative;
        z-index:20;
    }
</style>

url_cam<input id="url_cam" type="text" value= "{{ camera.fields.url }}" disabled style="vertical-align: center; height: 10%; width:30%;"/>
<button id="edit_url_button" type="submit" >Edit url</button>
<div id="canvas_container" >
    <img id="img" width="800" height="400" src="{{ camera.fields.url }}" />
    <canvas id="myCanvas" width="800" height="400">
        Your browser does not support the HTML5 canvas tag.
    </canvas> 
   
</div>

<button id="edit_roi_button" type="button" >Edit Detection Zone</button>

<!--<canvas id="myChart" width="500" height="200"></canvas>-->
<script type="text/javascript" src="http://code.jquery.com/jquery-1.10.0.min.js"></script>
<script type="text/javascript" src="{% static 'js/Chart.min.js' %}"></script>
<script type="text/javascript">
   
</script>
<script>
    
    DATA = {
        id_cam: "{{ camera.pk }}",
        x: 0,
        y: 0,
        width: 0,
        height: 0,
        detection_zone: [],
        url:"{{ camera.fields.url }}"
    }
   /* $.getJSON("{% url 'pedestrian_detector:get_reports' %}", function(data) {
           // $('#container').highcharts(data);
    });*/
    DATA.detection_zone={{ detection_zone.fields.detection_zone|safe }}
    DATA_CONTAINER = {DATA}
    var toggle_roi=false
    var edit_roi_button = document.getElementById("edit_roi_button")
    edit_roi_button.onclick=function(){
        
        if(toggle_roi){
            toggle_roi=false
            edit_url_button.innerHTML="Edit zone detection"
            DATA.width = Math.abs(endX-initX)
            DATA.height = Math.abs(endY-initY)

            if(endX - initX < 0){
                initX = endX
            }
            if(endY - initY < 0){
                initY = endY
            }
            DATA.x = initX
            DATA.y = initY

            if(Math.abs(DATA.width) > 0 && Math.abs(DATA.height) > 0){

                $.getJSON("{% url 'pedestrian_detector:edit_roi' %}", DATA)
                .done(function (response) {
                    console.log("response", response)
                })
                .fail(function (response, textStatus, error) {
                    console.log(response, textStatus, error)
                })
            }
        }
        else{
            edit_url_button.innerHTML="Save zone detection"
            toggle_roi=true
            
        }
    }
    var image = document.getElementById("img")
    var toggle_url=false
    var edit_url_button = document.getElementById("edit_url_button")
    edit_url_button.onclick=function(){
        if(toggle_url){
            edit_url_button.innerHTML="Edit url"
            DATA.url=url_cam.value
            image.src=url_cam.value
            toggle_url=false
            url_cam.disabled=true
            $.getJSON("{% url 'cameras:edit_url_camera' %}", DATA)
            .done(function (response) {
                console.log("response", response)
            })
            .fail(function (response, textStatus, error) {
                console.log(response, textStatus, error)
            })
        }else{
            edit_url_button.innerHTML="Save url"
            toggle_url=true
            url_cam.disabled=false
        }
    }
    var url_cam = document.getElementById("url_cam")
    url_cam.value="{{ camera.fields.url }}"
   
    //CANVAS INIT
    var canvas = document.getElementById("myCanvas")
    var ctx = canvas.getContext("2d")
    ctx.beginPath()
    
    //USEFUL VARIABLES INIT
    var initX = 0
    var initY = 0
    var endX = 0
    var endY = 0
    var isMouseDown = false

    canvas.addEventListener('mousedown', function(e){
        initX = e.offsetX
        initY = e.offsetY
        isMouseDown = true
            console.log(endX,endY)
    })

    canvas.addEventListener('mouseup', function(e){
        isMouseDown = false
        console.log(endX,endY)
    })

    canvas.addEventListener('mousemove', function(e){
        if (isMouseDown && toggle_roi) {
            console.log(endX,endY)
            endX = e.offsetX
            endY = e.offsetY

            ctx.clearRect(0, 0, canvas.width, canvas.height)
            ctx.beginPath()

            ctx.strokeStyle = 'red'
            ctx.lineWidth = 5
            ctx.rect(initX, initY, endX - initX, endY - initY)
            ctx.stroke()
        }
    })

    function draw_roi(){

        ctx.clearRect(0, 0, canvas.width, canvas.height)
        ctx.beginPath()
        ctx.strokeStyle = 'black'
        ctx.lineWidth = 3
        ctx.rect(
            DATA.detection_zone[0],
            DATA.detection_zone[1],
            DATA.detection_zone[2],
            DATA.detection_zone[3]
        )
        ctx.stroke()
       
    }
    draw_roi()
   /* $.get('{% url "pedestrian_detector:line_chart_json" %}', function(data) {
        var ctx = $("#myChart").get(0).getContext("2d");
        console.log(data)
        new Chart(ctx, {
            type: 'line', data: data
        });
    });
*/
  
</script>
{% endblock %}
       